
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgphtjcnhnkizgooohmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFncGh0amNuaG5raXpnb29vaG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NjE3MTEsImV4cCI6MjA1OTUzNzcxMX0.HPWhKccgdJiTNwlZrzonkfq0yuKSYlLsvYNOc2Iqzcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
